Repository CoffeeDrivenDevelopment/Sangchu-Web, pull requests merged in 2024-04, with the labels that each got.

#7 #2 Design: css 1차 수정 등
  index.html
  package-lock.json
  package.json
  src/components/common/HomeBox.tsx
  src/components/ingredients/MarketList/MarketList.tsx
  src/components/report/ReportTargetPrice.tsx
  src/main.tsx
  src/pages/Home/Home.styled.ts
  src/pages/Home/Home.tsx
  src/pages/recipe/RecipeMovie.tsx
  src/services/recommend/getRecommendIngredients.json
  src/services/recommend/getRecommendRecipe.json
  src/stores/useTargetPriceStore.ts
Labels: 🚑 fix, ♻️ refactor

#9 #8 Fix: 버그수정 및 예외처리 1차
  src/components/recipe/RecipeComments.tsx
  src/components/recipe/RecipeListCard.tsx
  src/components/report/ReportReasonable.tsx
  src/components/review/ReviewList.styled.ts
  src/components/user/MyAddress.tsx
  src/components/user/MyWishRecipeList.tsx
  src/pages/Home/Home.tsx
  src/pages/ingredients/Ingredients.tsx
  src/pages/ingredients/IngredientsDetail.tsx
  src/pages/user/MyMap.tsx
Labels: ✨ feature, 🚑 fix, ♻️ refactor

#12 차트 날짜 방향 변경 및 찜한 레시피 uri 수정(feat/#11)
  src/components/user/MyWishRecipeList.tsx
  src/pages/Home/Home.tsx
  src/pages/ingredients/IngredientsDetail.tsx
Labels: 🚑 fix

#13 분석리포트 차트 인덱스 수정(feat/#11)
  src/components/report/ReportGraphs.tsx
Labels: 🚑 fix

#15 최신순, 인기순 버튼 삭제(#14)
  src/components/review/ReviewList.styled.ts
  src/components/review/ReviewList.tsx
  src/pages/ingredients/IngredientList.tsx
Labels: ✨ feature

#19 식재료 가격 상승, 하락 api 응답 변경 작업(#18)
  src/components/common/IconBox.tsx
  src/pages/ingredients/Ingredients.tsx
  src/services/ingredient/getAsc.ts
  src/services/ingredient/getDesc.ts
Labels: ♻️ refactor

#21 원화에 천원 단위로 콤마 표시(#20)
  src/components/ingredients/MarketList/MarketList.tsx
  src/components/report/ReportPredict.tsx
  src/components/report/ReportReasonable.tsx
  src/components/user/MyPriceList.tsx
  src/pages/Home/Home.tsx
  src/pages/ingredients/IngredientsDetail.tsx
Labels: ♻️ refactor

#23 숟가락 색깔 바꾸기(feat/#22)
  src/components/user/MyWishRecipeList.tsx
Labels: 🚑 fix

#25 #24 지정목표가 없을때 출력메시지 추가
  src/components/user/MyPriceList.tsx
Labels: ♻️ refactor

#32 #31 Fix: 가격 0일때 예외처리 수정
  src/pages/ingredients/IngredientsDetail.tsx
Labels: 🚑 fix

#34 #33 Fix: 온오프라인 가격추이 가격 출력 버그수정
  src/pages/ingredients/IngredientsDetail.tsx
Labels: 🚑 fix

#35 Fix: 온오프라인 가격추이 버그 다시 수정
  src/pages/ingredients/IngredientsDetail.tsx
Labels: 🚑 fix

#30 #10 Design: css 2차 수정
  src/components/recipe/RecipeComments.tsx
  src/components/recipe/RecipeInfo.styled.ts
  src/components/recipe/RecipeListCard.tsx
  src/components/recipe/RecipeReplyComments.tsx
  src/components/report/ReportTargetPrice.tsx
  src/components/review/ReviewList.styled.ts
  src/components/review/ReviewList.tsx
  src/components/user/MyAddress.tsx
  src/components/user/MyWishRecipeList.tsx
  src/pages/recipe/RecipeMovie.tsx
  src/pages/review/ReviewDetail.tsx
  src/pages/review/ReviewWrite.tsx
  src/services/review/deleteReview.ts
Labels: ♻️ refactor

#36 마이페이지 주소설정 위치 변경(feat/#24)
  src/pages/user/MyProfile.tsx
  src/pages/user/Profile.styled.ts
Labels: ♻️ refactor

#38 #31 Fix: 버그수정 및 store 삭제
  src/@types/global/Address.d.ts
  src/@types/global/Ingredient.d.ts
  src/components/ingredients/MarketList/MarketList.tsx
  src/components/report/ReportGraphs.tsx
  src/components/report/ReportTargetPrice.tsx
  src/components/user/MyAddress.tsx
  src/components/user/MyPriceList.tsx
  src/pages/ingredients/IngredientsDetail.tsx
  src/pages/user/RegisterAddress.tsx
  src/services/user/getUserTargetPrice.ts
  src/services/user/patchUserAddress.ts
  src/stores/useAddressStore.ts
  src/stores/useTargetPriceStore.ts
Labels: 🚑 fix, 🔥 remove, ♻️ refactor

#40 #39 Design: alert 디자인 빠진 부분 추가
  src/components/recipe/RecipeReplyComments.tsx
  src/components/user/MyAddress.tsx
  src/pages/review/ReviewWrite.tsx
  src/pages/user/RegisterAddress.tsx
Labels: ✨ feature

#43 #42 Design: css 3차 수정
  src/components/common/HelpModal.tsx
  src/components/recipe/RecipeComments.tsx
  src/components/recipe/RecipeInfo.tsx
  src/components/recipe/RecipeReplyComments.tsx
  src/components/report/ReportGraphs.tsx
  src/components/report/ReportPredict.tsx
  src/components/report/ReportReasonable.tsx
  src/components/report/ReportTargetPrice.tsx
  src/components/review/ReviewList.styled.ts
  src/components/user/MyAddress.tsx
  src/hooks/commentFormatDate.ts
  src/hooks/graphFormatDate.ts
  src/hooks/updateFormatDate.ts
  src/pages/Home/Home.tsx
  src/pages/ingredients/IngredientsDetail.tsx
  src/pages/review/ReviewDetail.tsx
  src/pages/user/MyMap.tsx
Labels: ✨ feature, 🚑 fix, ♻️ refactor

#46 #45 Design: css 4차 수정
  src/components/review/ReviewList.styled.ts
  src/components/review/ReviewList.tsx
  src/components/user/MyReviewList.tsx
Labels: ♻️ refactor

#47 마이페이지-목표가 온/오프라인 차트값을 최신순으로 정렬
  package-lock.json
  src/components/user/MyPriceList.tsx
Labels: 🐛 bug

#49 #48 resolve: 데이터 size 최대로 변경
  src/components/recipe/RecipeListCard.tsx
  src/components/recipe/RecipeReplyComments.tsx
  src/components/review/ReviewList.tsx
Labels: ♻️ refactor
